### ISSUE TITLE
Does this project use semver?

### ISSUE THREAD

**Issue by Pezmc** [adopted-ember-addons/ember-cli-sass#183]
We've just upgraded from 6.1.3 to 7.0.0 but I'm having trouble locating the "incompatible API changes", made [between the two versions](https://github.com/aexmachina/ember-cli-sass/compare/v6.1.3...v7.0.0).

Am I overlooking something? Or do you not follow [semver](https://semver.org/)?

Thanks!

**Comment by jelhan** [comment]
Upgrading from v6 to v7 is a major upgrade. You should expect incompatible API changes between such upgrades accordingly to SemVer.
