### ISSUE TITLE
broccoli sass source maps outdated 

### ISSUE THREAD

**Issue by patricklx** [adopted-ember-addons/ember-cli-sass#233]
Hi, currently ember-cli-sass uses broccoli-sass-source-maps, which still uses a legacy JS API. https://github.com/sass/dart-sass/issues/1687
I made a PR to https://github.com/simonexmachina/broccoli-sass-source-maps/pull/32, but it looks like simonexmachine is not active on github anymore (at least from seeing recent activity).
Maybe the package should be copied into ember-cli-sass?

**Comment by knownasilya** [comment]
If we could move it to adopted add-ons that would be preferable I think. Think you could initiate that?

**Comment by patricklx** [comment]
that would require a transfer, right. But last activity from simonexmachina November 2020... Not sure if hes gonna respond

**Comment by knownasilya** [comment]
Worth trying at least. I'm sure other addons use that library too.

**Comment by patricklx** [comment]
It's now an adopted addon
